version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pedidoyapo_staging
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_staging_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/${APP_OWNER}/${APP_REPO}:${APP_IMAGE_TAG}
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pedidoyapo_staging?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - "8086:8085"
    volumes:
      - ./uploads:/app/uploads

volumes:
  db_staging_data: {}
